import { ReactElement } from "react";

export interface DataType {
  key: number;
  esfera: string;
  orgao: string;
  tipo: string;
  qtdMin: number;
  qtdMax: number;
  descricao: string;
  modelo: string;
  valor: string;
  filtro: string;

}

export const data: DataType[] = [
  {
    key: 1,
    esfera: "Federal",
    orgao: "Exército",
    tipo: "Computador",
    qtdMin: 10,
    qtdMax: 248,
    descricao:
      "Computador Desktop i3| 4GB RAM| HD de 1Tb| Fonte 450W| 6x USB 2.0| HDMI, VGA| Som, teclado e mouse",
    modelo: "NTC",
    valor: "R$ 1.350,00",
    filtro: "Computadores",
  },
  {
    key: 2,
    esfera: "Federal",
    orgao: "Prefeitura Muncipal (SC)",
    tipo: "Computador",
    qtdMin: 15,
    qtdMax: 150,
    descricao:
      "Computador Processador 3.0Ghz, turbo 3.2Ghz| 4GB RAM| HD de 250GB | Placa de vídeo integrada de 1GB| Windows 7 Professional",
    modelo: "-",
    valor: "R$ 1.550,00",
    filtro: "Computadores",
  },
  {
    key: 3,
    esfera: "Federal",
    orgao: "Hospital Universitário (RJ)",
    tipo: "Computador",
    qtdMin: 5,
    qtdMax: 93,
    descricao:
      "Computador Desktop i7| 4GB RAM| HD de 500GB | Fonte 300W| Gravador DVD| 6x USB 2.0| Windows 7 Professional",
    modelo: "NTC",
    valor: "R$ 1.800,00",
    filtro: "Computadores",
  },
  {
    key: 4,
    esfera: "Municipal",
    orgao: "Prefeitura Muncipal (PR)",
    tipo: "Computador",
    qtdMin: 40,
    qtdMax: 800,
    descricao: "Computador Microcomputador com processador duplo completo",
    modelo: "-",
    valor: "R$ 2.190,00",
    filtro: "Computadores",
  },
  {
    key: 5,
    esfera: "Federal",
    orgao: "Universidade Federal (MG)",
    tipo: "Lousa",
    qtdMin: 8,
    qtdMax: 10,
    descricao: 'Lousa Interativa 80" Toque do Dedo',
    modelo: "TG-4180",
    valor: "R$ 1.999,99",
    filtro: "Lousa",
  },
  {
    key: 6,
    esfera: "Federal",
    orgao: "Universidade Federal (MG)",
    tipo: "Lousa",
    qtdMin: 1,
    qtdMax: 4,
    descricao: 'Lousa Interativa 80" Toque do Dedo',
    modelo: "TG-4180",
    valor: "R$ 2.700,00",
    filtro: "Lousa",
  },
  {
    key: 7,
    esfera: "Federal",
    orgao: "Exército",
    tipo: "Lousa",
    qtdMin: 5,
    qtdMax: 15,
    descricao: 'Lousa Interativa 96" Toque do dedo',
    modelo: "TI-4196",
    valor: "R$ 3.350,00",
    filtro: "Lousa",
  },
  {
    key: 8,
    esfera: "Federal",
    orgao: "Agência Espacial Brasileira",
    tipo: "Lousa",
    qtdMin: 1,
    qtdMax: 2,
    descricao: 'Lousa Interativa 96" Toque do dedo',
    modelo: "TI-4196",
    valor: "R$ 5.650,00",
    filtro: "Lousa",
  },
  {
    key: 9,
    esfera: "Municipal",
    orgao: "Pref. Municipal (SC)",
    tipo: "Sala Interativa",
    qtdMin: 1,
    qtdMax: 36,
    descricao:
      'Lousa Interativa 80" Toque do dedo, projetor multimídia e sistema de som',
    modelo: "Kit Sala Interativa",
    valor: "R$ 14.237,00",
    filtro: "Lousa",
  },
  {
    key: 10,
    esfera: "Federal",
    orgao: "Grupamento de Apoio Logístico da Aeronáutica",
    tipo: "Nobreak",
    qtdMin: 1,
    qtdMax: 250,
    descricao:
      "Nobreak Compact Plus Semi Senoidal 1200 VA / 600 W com 2 baterias de 7Ah com USB",
    modelo: "90.C0.012004",
    valor: "R$ 438,00",
    filtro: "Nobreak",
  },
  {
    key: 11,
    esfera: "Federal",
    orgao: "3° Centro de Telemática de Área",
    tipo: "Nobreak",
    qtdMin: 1,
    qtdMax: 30,
    descricao:
      "Nobreak Premium Senoidal Dupla Conversão Rack 3000 VA / 2700 W com 10 baterias de 9Ah + Trilho 120V ou 220V",
    modelo: "92.A0.030702",
    valor: "R$ 3.553,00",
    filtro: "Nobreak",
  },
  {
    key: 12,
    esfera: "Federal",
    orgao: "Empresa Brasileira de Comunicações",
    tipo: "Nobreak",
    qtdMin: 1,
    qtdMax: 10,
    descricao:
      "Nobreak Premium Senoidal Dupla Conversão Rack 3000 VA / 2700 W com 10 baterias de 9Ah + Trilho 120V ou 220V",
    modelo: "92.A0.030702",
    valor: "R$ 4.090,00",
    filtro: "Nobreak",
  },
  {
    key: 13,
    esfera: "Federal",
    orgao: "25ª Circunscrição de Serviço Militar",
    tipo: "Nobreak",
    qtdMin: 1,
    qtdMax: 57,
    descricao: "Nobreak Laser Senoidal 5000 VA / 3500 W com 12 baterias de 9Ah",
    modelo: "91.D0.050000",
    valor: "R$ 4.600,00",
    filtro: "Nobreak",
  },
  {
    key: 14,
    esfera: "Federal",
    orgao: "IFECT Baiano - Guanambi",
    tipo: "Nobreak",
    qtdMin: 1,
    qtdMax: 4,
    descricao:
      "Nobreak Laser Senoidal Dupla Conversão 5000VA / 4000 W com 16 baterias de 9Ah, Entrada 220V, Saída Bivolt",
    modelo: "92.B0.050300",
    valor: "R$ 8.134,00",
    filtro: "Nobreak",
  },
  {
    key: 15,
    esfera: "Federal",
    orgao: "Base Aérea de Natal",
    tipo: "Nobreak",
    qtdMin: 1,
    qtdMax: 10,
    descricao:
      "Nobreak Expert Senoidal Dupla Conversão 10 KVA / 8KW com módulo de baterias externo: 20 baterias de 17Ah",
    modelo: "92.C0.100440",
    valor: "R$ 11.280,00",
    filtro: "Nobreak",
  },
  {
    key: 16,
    esfera: "Federal",
    orgao: "Tribunal Regional do Trabalho	",
    tipo: "Suporte Para TV Interativa",
    qtdMin: 1,
    qtdMax: 5,
    descricao: "Suporte para TV Interativa TRACEBoard",
    modelo: "Suporte TRACEBoard	",
    valor: "R$ 3.200,00",
    filtro: "Interativo",
  },
  {
    key: 17,
    esfera: "Federal",
    orgao: "Exército",
    tipo: "TV Interativa",
    qtdMin: 1,
    qtdMax: 9,
    descricao: "TV Interativa 70' Quinyx",
    modelo: "QTP-7002",
    valor: "R$ 24.580,00",
    filtro: "Interativo",
  },
  {
    key: 18,
    esfera: "Federal",
    orgao: "Exército",
    tipo: "Monitor",
    qtdMin: 10,
    qtdMax: 274,
    descricao: "Monitor LED 19,5' 1600x900",
    modelo: "LG",
    valor: "R$ 476,00",
    filtro: "Monitores",
  },
  {
    key: 19,
    esfera: "Federal",
    orgao: "Exército",
    tipo: "Monitor",
    qtdMin: 10,
    qtdMax: 245,
    descricao: "Monitor LED 21,5' Full HD",
    modelo: "LG",
    valor: "R$ 565,66",
    filtro: "Monitores",
  },
  {
    key: 20,
    esfera: "Federal",
    orgao: "Exército",
    tipo: "Monitor",
    qtdMin: 10,
    qtdMax: 199,
    descricao: "Monitor LED 23' Full HD",
    modelo: "LG",
    valor: "R$ 650,00",
    filtro: "Monitores",
  },
  {
    key: 21,
    esfera: "Estadual",
    orgao: "Comissão Central (MA)",
    tipo: "Scanner",
    qtdMin: 1,
    qtdMax: 1,
    descricao: "Scanner - Velocidade 60 PPM / 120 IPM",
    modelo: "AV220D2+",
    valor: "R$ 4.200,00",
    filtro: "Scanner",
  },
  {
    key: 22,
    esfera: "Federal",
    orgao: "Aeronáutica (DF)",
    tipo: "Totem",
    qtdMin: 5,
    qtdMax: 90,
    descricao: "Totem 17' com impressora térmica",
    modelo: "QTT-1700",
    valor: "R$ 6.950,00	",
    filtro: "Totem",
  },
  {
    key: 23,
    esfera: "Municipal",
    orgao: "Hospital (RS)",
    tipo: "Totem",
    qtdMin: 1,
    qtdMax: 5,
    descricao: "Totem multitooch 18,5'",
    modelo: "TT-2104",
    valor: "R$ 9998,00",
    filtro: "Totem",
  },
  {
    key: 24,
    esfera: "Municipal",
    orgao: "Hospital (RS)",
    tipo: "Totem",
    qtdMin: 1,
    qtdMax: 5,
    descricao: "Totem multitooch 40'",
    modelo: "TT-4004",
    valor: "R$ 14.500,00",
    filtro: "Totem",
  },
];
